version: '3'
services:
  scraper:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
     - "5000:5000"
    depends_on:
      - redis
  redis:
    image: redis/redis-stack-server
    ports:
      - "6379:6379"