# .github/workflows/test.yml
name: Workflow
on: [push, pull_request]

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: chartboost/ruff-action@v1
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
    
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"
    
      - name: Install pipenv
        run: |
          python -m pip install --upgrade pipenv wheel
    
      - name: Cache pipenv
        uses: actions/cache@v1
        id: cache-pipenv
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}
    
      - name: Install dependencies
        if: steps.cache-pipenv.outputs.cache-hit != 'true'
        run: pipenv install --dev
        
      - name: Install requirements
        run: pipenv install -r requirements.txt
    
      - name: Run PyTest
        run: pipenv run pytest
